config/routes.rb
Rails.application.routes.draw do
  root '/', controller: 'issues', action: :index
  get '/', controller: 'issues', action: :index

  resources :issues
  resources :comments, only: [:create]
  resources :tags, only: [:index, :show], param: :slug
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  belongs_to :issue, inverse_of: :comments, counter_cache: :comment_count

  validates :content, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
end

app/models/issue.rb
# frozen_string_literal: true

class Issue < ApplicationRecord
  include AASM
  include SearchCop

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_many :comments
  has_many :issue_tags
  has_many :tags, through: :issue_tags

  validates :title, presence: true, length: { maximum: 255, minimum: 1 }
  validates :content, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

  aasm column: :issue_state do
    state :opening, initial: true
    state :discussing
    state :closed

    event :open do
      transitions from: :closed, to: :opening
    end

    event :discuss do
      transitions from: :opening, to: :discussing
    end

    event :close do
      transitions from: :discussing, to: :closed
    end
  end

  search_scope :search do
    attributes :title, :content
    attributes comment: ['comments.content']
  end
end

app/models/issue_tag.rb
# frozen_string_literal: true

class IssueTag < ApplicationRecord
  belongs_to :issue
  belongs_to :tag
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :issue_tags
  has_many :issues, through: :issue_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_issue, only: :create

  def create
    @comment = Comment.new(permitted_params)

    unless @comment.valid?
      flash[:erorr] = @comment.errors.full_messages
      return redirect_to(issue_path(id: permitted_params[:issue_id]))
    end

    @issue.comments << @comment

    flash[:success] = '回答を登録しました'
    redirect_to issue_path(id: @comment.issue_id)
  end

  private

  def permitted_params
    params.require(:comment).permit(:issue_id, :email, :content)
  end

  def find_issue
    @issue = Issue.find(permitted_params[:issue_id])
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :build_issues, only: :index
  before_action :build_issue, onlye: :new
  before_action :build_comment, only: :show
  before_action :find_issue, only: %i[show update]
  before_action :find_comments, only: :show
  before_action :find_tags, only: :show

  def index
  end

  def new
  end

  def create
    @issue = Issue.new(permitted_params)
    unless @issue.valid?
      flash[:error] = @issue.errors.full_messages
      return render :new
    end

    @issue.save!

    flash[:success] = '質問を登録しました'
    redirect_to issues_path
  end

  def update

    unless @issue.update(issue_state: params[:issue_state])
      flash[:error] = ['ステータスの更新に失敗しました']
    else
      flash[:success] = 'ステータスを更新しました'
    end

    redirect_to issue_path(id: params[:id])
  end

  private

  def permitted_params
    params.require(:issue).permit(:email, :title, :content)
  end

  def build_issues
    @issues = IssueDecorator.decorate_collection(
      Issue.all.order(updated_at: :desc).page(params[:page])
    )

    if params[:search].present?
      @issues = @issues.search(params[:search])
    end
  end

  # Build a new Issue instance
  def build_issue
    @issue = Issue.new
  end

  def build_comment
    @comment = Comment.new
  end

  def find_issue
    @issue = Issue.find(params[:id]).decorate
  end

  def find_comments
    @comments = CommentDecorator.decorate_collection(
      @issue.comments
    )
  end

  def find_tags
    @tags = TagDecorator.decorate_collection(
      @issue.tags
    )
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  before_action :build_tags, only: :index
  before_action :find_tag_and_issues, only: :show

  def index
  end

  def show
    return render('tags/tag_not_found') if @tag.blank?
  end

  private

  def build_tags
    @tags = TagDecorator.decorate_collection(
      Tag.all.order(updated_at: :desc).page(params[:page])
    )
  end

  def find_tag_and_issues
    @tag = Tag.find_by(name: params[:slug])
    @issues = IssueDecorator.decorate_collection(
      @tag.issues.order(updated_at: :desc).page(params[:page])
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/comments/_comment_item.html.erb
<div class="row">
    <div class="col s4">
        <p><%= comment.email %></p>
    </div>
    <div class="col s8">
        <%= comment.content %>
    </div>
</div>

app/views/comments/_comment_items.html.erb
<div class="row">
    <%- if comments.length <= 0 %>
        <p class="center">回答はまだありません。</p>
    <%- else %>
        <%- comments.each do |comment| %>
            <div class="col s12">
                <%= render 'comments/comment_item', comment: comment %>
            </div>
        <%- end %>
    <%- end %>
</div>

app/views/comments/_comment_list.html.erb
<div class="col s12">
    <div class="section">
        <h4>回答一覧</h4>
        <div class="divider"></div>
        <%= render 'comments/comment_items', comments: @comments %>
    </div>
</div>

app/views/comments/_form.html.erb
<div class="row">
    <div class="col s12">
        <h5>回答を書く</h5>
    </div>
    <%= simple_form_for @comment do |f| %>
        <%= f.input(:issue_id, as: :hidden, input_html: { value: issue_id }) if issue_id.present? %>
        <div class="col s3">
            <%= f.input :email, label: 'メールアドレス' %>
        </div>
        <div class="col s6">
            <%= f.input :content, label: '回答内容', input_html: { class: %(materialize-textarea) }%>
        </div>
        <div class="col s3">
            <%= f.button :button, class: %(waves-effect waves-light btn right) do %>
                <i class="material-icons left small">create</i>
                回答を登録
            <%- end %>
        </div>
    <%- end %>
</div>

app/views/issues/_issues.html.erb
<div class="col s12">
    <% if issues.blank? %>
        <p>質問はありません。</p>
    <% else %>
        <table class="striped">
            <thead>
                <tr>
                    <th>No</th>
                    <th>質問事項</th>
                    <th>ステータス</th>
                    <th>回答数</th>
                </tr>
            </thead>
            <tbody>
                <%- issues.each do |issue| %>
                    <tr>
                        <td><%= issue.id %></td>
                        <td><%= link_to issue_path(issue) do %>
                            <%= issue.title %>
                        <%- end %></td>
                        <td><%= issue.issue_state %></td>
                        <td><%= issue.comment_count %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <%= paginate issues %>
    <% end %>
</div>

app/views/issues/index.html.erb
<div class="row">
    <div class="col s9">
        <h4><%- if params[:search].present? %>キーワード: 「<%= params[:search] %>」の<%- end %>質問の一覧</h4>
    </div>
    <div class="input-field col s3">
        <%= form_tag issues_path, method: :get do %>
            <i class="material-icons prefix">search</i>
            <%= text_field_tag :search, '', placeholder: 'キーワードから検索', id: 'search' %>
        <%- end %>
    </div>
</div>

<div class="row">
    <%= render 'issues/issues', issues: @issues %>
</div>

<div class="fixed-action-btn">
    <a class="btn-floating btn-large red">
        <i class="large material-icons">add</i>
    </a>
    <ul>
        <li>
            <%= link_to new_issue_path, class: %(btn-floating green tooltipped), data: { tooltip: '質問を登録' } do %>
                <i class="small material-icons">create</i>
            <% end %>
        </li>
    </ul>
</div>

<script type="text/javascript">
document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.fixed-action-btn');
    var instances = M.FloatingActionButton.init(elems, {
        direction: 'top'
    });

    var elems = document.querySelectorAll('.tooltipped');
    var instances = M.Tooltip.init(elems, {
        position: 'left'
    });
});
</script>

app/views/issues/new.html.erb
<div class="row">
    <div class="col s12">
        <h3>質問を登録</h3>
        <%= simple_form_for @issue do |f |%>
            <%= f.input :email, label: 'メールアドレス' %>

            <%= f.input :title, label: 'タイトル' %>

            <%= f.input :content, label: '質問内容', input_html: { class: %(materialize-textarea) } %>

            <%= f.button :button, '質問を登録', class: %(waves-effect waves-light btn right) %>
        <% end %>
    </div>
</div>

app/views/issues/show.html.erb
<div class="row">
    <div class="col s6">
        <h5>No<%= @issue.id %>の詳細・回答</h5>
    </div>
    <div class="col s6">
        <p class="right">
            登録日:<%= @issue.created_at %> /
            更新日:<%= @issue.updated_at %>
        </p>
    </div>

    <div class="col s12">
        <div class="row">
            <div class="col s12">
                <div class="section">
                    <h4><%= @issue.title %></h4>
                    <div class="divider"></div>
                </div>
            </div>
            <div class="col s9">
                <div class="content">
                    <%= @issue.content %>
                </div>
            </div>
            <div class="col s3">
                <div class="row">
                    <div class="col s3">
                        <h6>タグ</h6>
                    </div>
                    <div class="col s9">
                        <a href="#" class="btn-small right z-depth-1">
                            <i class="material-icons left">label</i>タグを登録
                        </a>
                    </div>
                </div>
                <% if @tags.blank? %>
                    <p>タグは設定されていません。</p>
                <% else %>
                    <ul>
                    <%- @tags.each do |tag| %>
                        <li class="left issue-tag"><%= link_to tag_path(slug: tag.name) do %>
                            <%= tag.name %>
                        <% end %></li>
                    <% end %>
                    </ul>
                <% end %>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <%= render 'comments/comment_list', comments: @comments %>
    <%= render('comments/form', issue_id: @issue.id) unless @issue.closed? %>
</div>

<div class="row">
    <div class="col s12">
        <p class="center">
            <%= link_to issues_path, class: %(waves-effect waves-teal btn-flat white) do %>
                <i class="material-icons left">arrow_back</i>
                一覧へ戻る
            <%- end %>
        </p>
    </div>
</div>

<%- unless @issue.closed? %>
<div class="fixed-action-btn">
    <a class="btn-floating btn-large red">
        <i class="large material-icons">style</i>
    </a>
    <ul>
        <li>
            <%= link_to issue_path(@issue, issue_state: :closed), class: %(btn-floating gray tooltipped), data: { tooltip: '質問をクローズ', method: 'put' } do %>
                <i class="small material-icons">close</i>
            <% end %>
        </li>
        <li>
            <%= link_to issue_path(@issue, issue_state: :discussing), class: %(btn-floating blue tooltipped), data: { tooltip: 'ディスカッション開始', method: 'put' } do %>
                <i class="small material-icons">record_voice_over</i>
            <% end %>
        </li>
    </ul>
</div>

<script type="text/javascript">
document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.fixed-action-btn');
    var instances = M.FloatingActionButton.init(elems, {
        direction: 'top'
    });

    var elems = document.querySelectorAll('.tooltipped');
    var instances = M.Tooltip.init(elems, {
        position: 'left'
    });
});
</script>
<%- end %>

app/views/layouts/_toast.html.erb
<script type="text/javascript">
<%- if flash[:success] %>
    M.toast({ html: '<%= flash[:success].html_safe %>' })
<%- elsif flash[:notice] %>
    M.toast({ html: '<%= flash[:notice].join("<br />").html_safe %>' })
<%- elsif flash[:error] %>
    M.toast({ html: '<%= flash[:error].join("<br />").html_safe %>' })
<%- end %>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>HelpDesk</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <nav>
            <div class="nav-wrapper">
                <div class="row">
                    <div class="col s12">
                        <a class="brand-logo" href="<%= root_path %>">Help Desk</a>
                        <ul id="nav-mobile" class="right hide-on-med-and-down">
                            <li><%= link_to tags_path do %>
                                <i class="material-icons">label_outline</i>
                            <% end %></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

        <div class="container">
            <%= yield %>
        </div>

        <%= render 'layouts/toast' %>
    </body>
</html>

app/views/tags/index.html.erb
<div class="col s12">
    <div class="section">
        <h3>登録タグ一覧</h3>
        <div class="divider"></div>
        <div class="content">
            <%- if @tags.blank? %>
            <% else %>
                <ul>
                    <%- @tags.each do |tag| %>
                        <li><%= link_to tag_path(slug: tag.name) do %>
                            <%= tag.name %>
                        <% end %></li>
                    <% end %>
                </ul>
            <% end %>
        </div>
    </div>
</div>

app/views/tags/show.html.erb
<div class="col s12">
    <div class="section">
        <h3><%= @tag.name %>が登録された質問一覧</h3>
        <div class="divider"></div>
        <div class="content">
            <%= render 'issues/issues', issues: @issues %>
        </div>
    </div>
</div>